In [44]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
import numpy as np

In [12]:
rs = 123

In [2]:
rating_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/ratings.csv"
user_emb_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/user_embeddings.csv"
item_emb_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/course_embeddings.csv"

In [3]:
rating_df = pd.read_csv(rating_url)

In [4]:
rating_df.head()

user        item  rating
0  1889878    CC0101EN     3.0
1  1342067    CL0101EN     3.0
2  1990814  ML0120ENv3     3.0
3   380098    BD0211EN     3.0
4   779563    DS0101EN     3.0

In [5]:
# Load user embeddings
user_emb = pd.read_csv(user_emb_url)
# Load item embeddings
item_emb = pd.read_csv(item_emb_url)

In [6]:
user_emb.head()

user  UFeature0  UFeature1  UFeature2  UFeature3  UFeature4  UFeature5  \
0  1889878   0.080721  -0.129561   0.087998   0.030231   0.082691  -0.004176   
1  1342067   0.068047  -0.112781   0.045208  -0.007570  -0.038382   0.068037   
2  1990814   0.124623   0.012910  -0.072627   0.049935   0.020158   0.133306   
3   380098  -0.034870   0.000715   0.077406   0.070311  -0.043007  -0.035446   
4   779563   0.106414  -0.001887  -0.017211  -0.042277  -0.074953  -0.056732   

   UFeature6  UFeature7  UFeature8  UFeature9  UFeature10  UFeature11  \
0  -0.003480   0.091464  -0.040247   0.018958   -0.153328   -0.090143   
1   0.114949   0.104128  -0.034401   0.004011    0.064832    0.165857   
2  -0.035366  -0.156026   0.039269   0.042195    0.014695   -0.115989   
3   0.032846  -0.060944   0.112384   0.002114    0.090660   -0.068545   
4   0.074610  -0.019367  -0.031341   0.064896   -0.048158   -0.047309   

   UFeature12  UFeature13  UFeature14  UFeature15  
0    0.082830   -0.058721    0.057929   -0.001472  
1   -0.004384    0.053257    0.014308    0.056684  
2    0.031158    0.102021   -0.020601    0.116488  
3    0.008967    0.063962    0.052347    0.018072  
4   -0.007544    0.010474   -0.032287   -0.083983

In [7]:
item_emb.head()

item  CFeature0  CFeature1  CFeature2  CFeature3  CFeature4  \
0    CC0101EN   0.009657  -0.005238  -0.004098   0.016303  -0.005274   
1    CL0101EN  -0.008611   0.028041   0.021899  -0.001465   0.006900   
2  ML0120ENv3   0.027439  -0.027649  -0.007484  -0.059451   0.003972   
3    BD0211EN   0.020163  -0.011972  -0.003714  -0.015548  -0.007540   
4    DS0101EN   0.006399   0.000492   0.005640   0.009639  -0.005487   

   CFeature5  CFeature6  CFeature7  CFeature8  CFeature9  CFeature10  \
0  -0.000361  -0.015081  -0.012229   0.015686   0.008401   -0.035495   
1  -0.017981   0.010899  -0.037610  -0.019397  -0.025682   -0.000620   
2   0.020496  -0.012695   0.036138   0.019965   0.018686   -0.010450   
3   0.014847  -0.005700  -0.006068  -0.005792  -0.023036    0.015999   
4  -0.000590  -0.010015  -0.001514  -0.017598   0.003590    0.016799   

   CFeature11  CFeature12  CFeature13  CFeature14  CFeature15  
0    0.009381   -0.032560   -0.007292    0.000966   -0.006218  
1    0.038803    0.000196   -0.045343    0.012863    0.019429  
2   -0.050011    0.013845   -0.044454   -0.001480   -0.007559  
3   -0.023480    0.015469    0.022221   -0.023115   -0.001785  
4    0.002732    0.005162    0.015031   -0.000877   -0.021283

In [8]:
# Merge user embedding features
user_emb_merged = pd.merge(rating_df, user_emb, how='left', left_on='user', right_on='user').fillna(0)
# Merge course embedding features
merged_df = pd.merge(user_emb_merged, item_emb, how='left', left_on='item', right_on='item').fillna(0)

In [9]:
merged_df.head()

user        item  rating  UFeature0  UFeature1  UFeature2  UFeature3  \
0  1889878    CC0101EN     3.0   0.080721  -0.129561   0.087998   0.030231   
1  1342067    CL0101EN     3.0   0.068047  -0.112781   0.045208  -0.007570   
2  1990814  ML0120ENv3     3.0   0.124623   0.012910  -0.072627   0.049935   
3   380098    BD0211EN     3.0  -0.034870   0.000715   0.077406   0.070311   
4   779563    DS0101EN     3.0   0.106414  -0.001887  -0.017211  -0.042277   

   UFeature4  UFeature5  UFeature6  ...  CFeature6  CFeature7  CFeature8  \
0   0.082691  -0.004176  -0.003480  ...  -0.015081  -0.012229   0.015686   
1  -0.038382   0.068037   0.114949  ...   0.010899  -0.037610  -0.019397   
2   0.020158   0.133306  -0.035366  ...  -0.012695   0.036138   0.019965   
3  -0.043007  -0.035446   0.032846  ...  -0.005700  -0.006068  -0.005792   
4  -0.074953  -0.056732   0.074610  ...  -0.010015  -0.001514  -0.017598   

   CFeature9  CFeature10  CFeature11  CFeature12  CFeature13  CFeature14  \
0   0.008401   -0.035495    0.009381   -0.032560   -0.007292    0.000966   
1  -0.025682   -0.000620    0.038803    0.000196   -0.045343    0.012863   
2   0.018686   -0.010450   -0.050011    0.013845   -0.044454   -0.001480   
3  -0.023036    0.015999   -0.023480    0.015469    0.022221   -0.023115   
4   0.003590    0.016799    0.002732    0.005162    0.015031   -0.000877   

   CFeature15  
0   -0.006218  
1    0.019429  
2   -0.007559  
3   -0.001785  
4   -0.021283  

[5 rows x 35 columns]

In [10]:
u_feautres = [f"UFeature{i}" for i in range(16)]
c_features = [f"CFeature{i}" for i in range(16)]

user_embeddings = merged_df[u_feautres]
course_embeddings = merged_df[c_features]
ratings = merged_df['rating']

# Aggregate the two feature columns using element-wise add
regression_dataset = user_embeddings + course_embeddings.values
regression_dataset.columns = [f"Feature{i}" for i in range(16)]
regression_dataset['rating'] = ratings
regression_dataset.head()

Feature0  Feature1  Feature2  Feature3  Feature4  Feature5  Feature6  \
0  0.090378 -0.134799  0.083900  0.046534  0.077417 -0.004537 -0.018561   
1  0.059437 -0.084740  0.067107 -0.009036 -0.031482  0.050057  0.125847   
2  0.152061 -0.014739 -0.080112 -0.009516  0.024130  0.153802 -0.048061   
3 -0.014707 -0.011257  0.073692  0.054763 -0.050547 -0.020599  0.027146   
4  0.112812 -0.001395 -0.011572 -0.032638 -0.080440 -0.057321  0.064595   

   Feature7  Feature8  Feature9  Feature10  Feature11  Feature12  Feature13  \
0  0.079236 -0.024561  0.027359  -0.188823  -0.080762   0.050271  -0.066013   
1  0.066517 -0.053798 -0.021671   0.064212   0.204660  -0.004188   0.007914   
2 -0.119888  0.059234  0.060882   0.004244  -0.166000   0.045002   0.057566   
3 -0.067012  0.106593 -0.020921   0.106658  -0.092025   0.024436   0.086183   
4 -0.020880 -0.048939  0.068486  -0.031359  -0.044577  -0.002381   0.025505   

   Feature14  Feature15  rating  
0   0.058894  -0.007689     3.0  
1   0.027170   0.076114     3.0  
2  -0.022081   0.108929     3.0  
3   0.029232   0.016287     3.0  
4  -0.033164  -0.105266     3.0

In [11]:
X = regression_dataset.iloc[:, :-1]
y = regression_dataset.iloc[:, -1]
print(f"Input data shape: {X.shape}, Output data shape: {y.shape}")

Input data shape: (233306, 16), Output data shape: (233306,)


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = rs, test_size= 0.3)

In [34]:
def fit_pred(model):
  model.fit(X_train,y_train)
  pred = model.predict(X_test)
  rmse = mean_squared_error(y_test,pred)
  return rmse, pred

In [37]:
ridge = linear_model.Ridge(alpha = 0.2)
rmse, pred = fit_pred(ridge)
print(rmse)
print(pred)

0.043953312914868446
[2.97006459 2.95399121 2.94914291 ... 2.976229   2.91781898 2.946684  ]


In [45]:
np.unique(pred)

array([2.88486403, 2.88643088, 2.88656093, ..., 3.02544008, 3.02761078,
       3.03088033])

In [46]:
ridge2 = linear_model.Ridge(alpha = 0.02)
rmse, pred = fit_pred(ridge2)
print(rmse)
print(pred)

0.04395331094696192
[2.97006858 2.95399118 2.9491423  ... 2.97623417 2.91781143 2.94668293]


In [47]:
ridge3 = linear_model.Ridge(alpha = 0.2, solver = 'sag')
rmse, pred = fit_pred(ridge3)
print(rmse)
print(pred)

0.04395331255349722
[2.97006443 2.95399117 2.94914218 ... 2.97622964 2.91781888 2.94668428]


In [48]:
lasso = linear_model.Lasso(alpha = 0.2)
rmse, pred = fit_pred(lasso)
print(rmse)
print(pred)

0.044252687736496245
[2.95268011 2.95268011 2.95268011 ... 2.95268011 2.95268011 2.95268011]


In [49]:
lasso2 = linear_model.Lasso(alpha = 0.02)
rmse, pred = fit_pred(lasso2)
print(rmse)
print(pred)

0.044252687736496245
[2.95268011 2.95268011 2.95268011 ... 2.95268011 2.95268011 2.95268011]


In [50]:
elastic1 = linear_model.ElasticNet(alpha = 0.2)
rmse, pred = fit_pred(elastic1)
print(rmse)
print(pred)

0.044252687736496245
[2.95268011 2.95268011 2.95268011 ... 2.95268011 2.95268011 2.95268011]


In [51]:
elastic2 = linear_model.ElasticNet(alpha = 0.02)
rmse, pred = fit_pred(elastic2)
print(rmse)
print(pred)

0.044252687736496245
[2.95268011 2.95268011 2.95268011 ... 2.95268011 2.95268011 2.95268011]
