In [26]:
import pandas as pd
import numpy as np
from sklearn import preprocessing


In [2]:
rs = 123

In [3]:
course_genres = ['Python', 'Database', 'MachineLearning']
courses = [['Machine Learning with Python', 1, 0, 1], ["SQL with Python", 1, 1, 0]]
courses_df = pd.DataFrame(courses, columns = ['Title'] + course_genres)
courses_df

Title  Python  Database  MachineLearning
0  Machine Learning with Python       1         0                1
1               SQL with Python       1         1                0

In [4]:
users = [['user0', 'Machine Learning with Python', 3], ['user1', 'SQL with Python', 2]]
users_df = pd.DataFrame(users, columns = ['User', 'Title', 'Rating'])
users_df

User                         Title  Rating
0  user0  Machine Learning with Python       3
1  user1               SQL with Python       2

In [5]:
# User 0 rated course 0 as 3 and course 1 as 0/NA (unknown or not interested)
u0 = np.array([[3, 0]])

In [7]:
C = courses_df[['Python', 'Database', 'MachineLearning']].to_numpy()
C

array([[1, 0, 1],
       [1, 1, 0]])

In [8]:
print(f"User profile vector shape {u0.shape} and course genre matrix shape {C.shape}")

User profile vector shape (1, 2) and course genre matrix shape (2, 3)


In [9]:
u0_weights = np.matmul(u0, C)
u0_weights

array([[3, 0, 3]])

In [10]:
course_genres

['Python', 'Database', 'MachineLearning']

In [11]:
# User 1 rated course 0 as 0 (unknown or not interested) and course 1 as 2
u1 = np.array([[0, 2]])
u1_weights = np.matmul(u1, C)
u1_weights

array([[2, 2, 0]])

In [12]:
weights = np.concatenate((u0_weights.reshape(1, 3), u1_weights.reshape(1, 3)), axis=0)
profiles_df = pd.DataFrame(weights, columns=['Python', 'Database', 'MachineLearning'])
profiles_df.insert(0, 'user', ['user0', 'user1'])

In [13]:
profiles_df

user  Python  Database  MachineLearning
0  user0       3         0                3
1  user1       2         2                0

In [15]:
new_courses = [['Python 101', 1, 0, 0], ["Database 101", 0, 1, 0], ["Machine Learning with R", 0, 0, 1]]
new_courses_df = pd.DataFrame(new_courses, columns = ['Title', 'Python', 'Database', 'MachineLearning'])
new_courses_df

Title  Python  Database  MachineLearning
0               Python 101       1         0                0
1             Database 101       0         1                0
2  Machine Learning with R       0         0                1

In [17]:
# Drop the title column
new_courses_df = new_courses_df.loc[:, new_courses_df.columns != 'Title']
course_matrix = new_courses_df.values
course_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
# course matrix shape
course_matrix.shape

(3, 3)

In [19]:
# Drop the user column
profiles_df = profiles_df.loc[:, profiles_df.columns != 'user']
profile_matrix = profiles_df.values
profile_matrix

array([[3, 0, 3],
       [2, 2, 0]])

In [20]:
profile_matrix.shape

(2, 3)

In [21]:
scores = np.matmul(course_matrix, profile_matrix.T)
scores

array([[3, 2],
       [0, 2],
       [3, 0]])

In [22]:
scores_df = pd.DataFrame(scores, columns=['User0', 'User1'])
scores_df.index = ['Python 101', 'Database 101', 'Machine Learning with R']

In [23]:
# recommendation score dataframe
scores_df

User0  User1
Python 101                   3      2
Database 101                 0      2
Machine Learning with R      3      0